import type { Config } from "tailwindcss";

// Tokens tomados de stitch_rm_design_system/atleta_pro_management/DESIGN.md
// para que el código quede visualmente idéntico a la maqueta aprobada.
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#2c1600",
        "primary-container": "#e8973a",
        error: "#F44336",
        "on-background": "#1a1c1c",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        secondary: "#4f6264",
        "surface-bright": "#f9f9f9",
        "inverse-primary": "#ffb86e",
        "surface-container-highest": "#e2e2e2",
        "on-surface-variant": "#534436",
        tertiary: "#006684",
        "on-secondary-fixed": "#0c1e20",
        surface: "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-white": "#FFFFFF",
        "on-tertiary-fixed": "#001f2a",
        "on-error-container": "#93000a",
        "surface-tint": "#8a5100",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f1f1",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        info: "#2196F3",
        "text-muted": "#757575",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#384a4c",
        border: "#D0D0D0",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#b6cacc",
        "inverse-surface": "#2f3131",
        "primary-fixed-dim": "#ffb86e",
        warning: "#FFC107",
        success: "#4CAF50",
        "tertiary-container": "#3cb5e2",
        "primary-fixed": "#ffdcbd",
        "tertiary-fixed": "#bee9ff",
        "on-primary-container": "#5c3400",
        outline: "#857464",
        "on-tertiary-container": "#004358",
        "surface-variant": "#e2e2e2",
        "surface-dim": "#dadada",
        background: "#f9f9f9",
        "secondary-container": "#cfe3e6",
        "secondary-fixed": "#d2e6e8",
        primary: "#8a5100",
        "tertiary-fixed-dim": "#69d3ff",
        "on-tertiary-fixed-variant": "#004d64",
        "surface-container": "#eeeeee",
        "outline-variant": "#d8c3b1",
        "on-primary-fixed-variant": "#693c00",
        "on-secondary-container": "#536668",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        base: "8px",
        xs: "4px",
        gutter: "24px",
        "container-max": "1280px",
        lg: "24px",
        md: "16px",
        sm: "8px",
        xl: "32px",
      },
      fontFamily: {
        "label-bold": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "body-sm": ["Hanken Grotesk"],
        "display-lg-mobile": ["Hanken Grotesk"],
        caption: ["Hanken Grotesk"],
        "data-mono": ["JetBrains Mono"],
      },
      fontSize: {
        "label-bold": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        caption: ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
